# Generated by Django 4.1.7 on 2023-03-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_task_captcha_task_captcha_code_task_captcha_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Inited", "Inited"),
                    ("Started", "Started"),
                    ("Transfered", "Transfered"),
                    ("SampleDLed", "Sampling Downloaded"),
                    ("Finished", "Finished"),
                ],
                default="Inited",
                editable=False,
                max_length=10,
            ),
        ),
    ]
