# Generated by Django 4.1.7 on 2023-03-19 12:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="shared_id",
            field=models.CharField(default="", max_length=50),
        ),
    ]
