# Generated by Django 4.1.7 on 2023-03-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0006_alter_task_captcha_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="full_download_now",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
