# Generated by Django 4.1.7 on 2023-07-10 09:46
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0008_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="retry_times",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
