# Generated by Django 4.1.7 on 2023-07-23 17:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0010_alter_task_full_download_now"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="shared_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="task",
            name="shared_link",
            field=models.CharField(
                help_text="Link, with or without password",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="shared_password",
            field=models.CharField(
                blank=True,
                help_text="Password, if not included in the shared link",
                max_length=4,
                null=True,
            ),
        ),
    ]
